inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
  CacheRootDirectory: tmp

# Esta métrica é um pouco redundante com a Metrics/AbcSize pois se o método tem muito código,
# provavelmente ele é complexo e a AbcSize irá pegar.
Metrics/MethodLength:
  Enabled: false

# Enforça sempre usar aspas duplas, evita ter que ficar pensando em qual situação usa simples ou dupla
# já que dependendo da interpolação vai ter que usar aspas duplas e não tem diferença de performance
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Desabilita documentação de classes obrigatória
Style/Documentation:
  Enabled: false

# Desabilita comentário 'frozen_string_literal: true' obrigatório em todos os arquivos
# A ideia dessa cop era facilitar a migração para o Ruby 3,
# pois todas as strings seriam imutáveis por padrão apartir dessa versão
# Porém a ideia foi abandonada, provavelmente essa cop vai ser desbilitada por padrão mais pra frente:
# https://github.com/rubocop-hq/rubocop/issues/7197
Style/FrozenStringLiteralComment:
  Enabled: false

# System tests não possuem uma classe que represente eles, por ser apenas views sendo testadas,
# por isso não faz sentido utilizar esse cop em system/views test.
RSpec/DescribeClass:
  Exclude:
    - spec/system/**/*.rb
    - spec/views/**/*.rb

# Desabilita tamanho máximo de blocos em arquivos que usam DSL própria, como rspec, rake, etc.
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - Rakefile
    - Guardfile
    - lib/tasks/**/*.rb
    - lib/tasks/*.rake
    - config/**/*.rb

# Obriga nomear as variáveis de exception como 'error'
# Padrão do rubocop é 'e', porém conflita com o Reek que não premite variáveis de uma letra
Naming/RescuedExceptionsVariableName:
  PreferredName: error

# Não e necessário utilizar 'super' no initialize ao herdar de ApplicationService.
# https://github.com/rubocop-hq/ruby-style-guide/issues/809
Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'

RSpec/FilePath:
  Exclude:
    - spec/requests/**/*.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: false

# System tests são lentos, cada expect faz carregar toda a página e executar o js, por isso,
# faz sentido utilizar mais de um expect dentro de cada example.
RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*.rb

RSpec/ExampleLength:
  Exclude:
    - spec/system/**/*.rb